version: '3.5'

services:
  backend:
    image: python:latest
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python main.py"

  frontend:
    image: node:latest
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: bash -c "npm i && npm start"
